# Generated by Django 3.1.7 on 2021-03-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jlibrary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='student',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='book',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='student',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Borrower',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
